- hosts: localhost
  become: true
  tasks:
  - name: Programok telepitese
    apt: 
      name: "{{ csomagok }}"
      state: present
      update_cache:  yes
    vars:
      csomagok:
        - sl
        - zsh
        - s3cmd
