- hosts: localhost
  become: true
  pre_tasks:
    - name: update repositories
      apt: update_cache=yes
      changed_when: False

  handlers:
    - name: restart_sshd
      service:
        name: sshd
        state: restarted

  tasks:
    - include: tasks/users.yml
    - include: tasks/packages.yml
    - include: tasks/cron.yml
    - include: tasks/gnome.yml
    - include: tasks/docker.yml
    - include: tasks/virtualbox.yml
    - include: tasks/authorized.yml
    - include: tasks/sshd_password.yml
    - include: tasks/grub_recovery.yml