- name: Add Opera Repository
  apt_repository:
    repo: "deb https://deb.opera.com/opera-stable/ stable non-free"
    filename: opera-stable.list
    state: present

- name: Add the Opera APT key
  apt_key:
    url: https://deb.opera.com/archive.key
    state: present

- name: Install opera
  apt:
    name: opera-stable
    update_cache: yes
    state: latest

