- name: Common programok telepitese mc curl opensh-server gdebi-core
  apt: 
    name: ['mc','curl','openssh-server','gdebi-core']
    state: present
    update_cache: yes

- name: Desktop programok telepitese 
  apt: name={{item}} state=present update_cache=yes
  with_items:
    - terminator
    - vlc
    - gnome-tweak-tool
    - guake
    - guake-indicator

- name: virtualbox telepitese.
  apt: name={{item}} state=present update_cache=yes
  with_items:
    - virtualbox
    - libgsoap-2.8.60
    - virtualbox-dkms
    - virtualbox-qt
