- name: grub_disable_recovery - 'resolved.conf DNS=8.8.8.8'
  lineinfile: 
    dest: /etc/systemd/resolved.conf
    regexp: '^#?DNS='
    line: 'DNS=8.8.8.8'
    backup: yes


- name: grub_disable_recovery - 'resolved.conf DNS=8.8.8.8'
  lineinfile: 
    dest: /etc/systemd/resolved.conf
    regexp: 'DNS=192.168.0.253'
    line: 'DNS=8.8.8.8'
    backup: yes
    
- name: grub_disable_recovery - 'resolved.conf FallbackDNS=1.1.1.1'
  lineinfile: 
    dest: /etc/systemd/resolved.conf
    regexp: '^#?FallbackDNS='
    line: 'FallbackDNS=1.1.1.1'
    backup: yes
