- name: Password based logins are disabled - '^#?AuthenticationMethods'
  lineinfile: dest=/etc/ssh/sshd_config regexp='^#?AuthenticationMethods' line='AuthenticationMethods publickey'
  
- name: Password based logins are disabled -'^#?PasswordAuthentication' 
  lineinfile: dest=/etc/ssh/sshd_config regexp='^#?PasswordAuthentication' line='PasswordAuthentication no'
  
- name: Password based logins are disabled - '^#?ChallengeResponseAuthentication'
  lineinfile: dest=/etc/ssh/sshd_config regexp='^#?ChallengeResponseAuthentication' line='ChallengeResponseAuthentication no'
  
- name: Password based logins are disabled - '^#?PubkeyAuthentication'
  lineinfile: dest=/etc/ssh/sshd_config regexp='^#?PubkeyAuthentication' line='PubkeyAuthentication yes'
#  notify: restart_sshd
