- name: update sshd config
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication.*yes'
    line: 'PasswordAuthentication=no'
  notify: restart_sshd

#handlers:
#  - name: restart_sshd
#    service:
#      name: sshd
#      state: restarted